### ISSUE TITLE
Authorization / permissions

### ISSUE THREAD

**Issue by buffcode** [pepakriz/gitlab-merger-bot#118]
First of all THANK YOU for this project. I've just installed the Docker image and seeing my daily routine being automated is an instant relief :)

Despite my relief I fear mis-usage of the bot, as now [every developer can assign a MR](https://docs.gitlab.com/ee/user/permissions.html#project-members-permissions) to the bot user and circumvent the [protected branch settings](https://docs.gitlab.com/ee/user/project/protected_branches.html).

It would be nice to have some kind of authorization / limitation who can command the bot.

Suggestions:
- The bot can check who assigned the MR to it and have a fixed list who is eligible to do so
- Reflect GitLab permissions:
  - Query [/projects/:id/members/all](https://docs.gitlab.com/ee/api/members.html#list-all-members-of-a-group-or-project-including-inherited-members) to get the user's permission in this project
  - Query [/projects/:id/repository/branches/:branch](https://docs.gitlab.com/ee/api/branches.html#get-single-repository-branch) to check `developers_can_merge`
  - accept MR if user could merge by himself, otherwise re-assign to user

**Comment by pepakriz** [comment]
Hi, glad to hear that you find this project useful.

Do you have an idea how to determine (without hooks) who made an assign? The only way I see is it should read changes (https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr-changes) or events (https://docs.gitlab.com/ee/api/events.html#list-currently-authenticated-users-events). Nothing that to be simple to implement.

**Comment by buffcode** [comment]
It should be possible with [`/todos`](https://docs.gitlab.com/ee/api/todos.html).

Eg. `https://gitlab.example.org/api/v4/todos?type=MergeRequest&action=assigned&state=pending` yields all ToDos for the current user (the bot) where the bot was assigned a MR by someone else.

<details>
  <summary>The response looks like this:</summary>

```json
[
    {
        "id": 6007,
        "project": {
            "id": 461,
            "description": "Sample project",
            "name": "Sample project",
            "name_with_namespace": "sample / project",
            "path": "sample-project",
            "path_with_namespace": "sample/project",
            "created_at": "2018-11-09T15:09:57.253+01:00"
        },
        "author": {
            "id": 1,
            "name": "Assigning User",
            "username": "assigning-user",
            "state": "active",
            "avatar_url": "https://gitlab.example.org/uploads/-/system/user/avatar/1/assigning-user.jpg",
            "web_url": "https://gitlab.example.org/assigning-user"
        },
        "action_name": "assigned",
        "target_type": "MergeRequest",
        "target": {
            "id": 4148,
            "iid": 679,
            "project_id": 461,
            "title": "plz merge me",
            "description": "",
            "state": "opened",
            "created_at": "2021-09-02T23:41:17.132+02:00",
            "updated_at": "2021-09-02T23:41:17.132+02:00",
            "merged_by": null,
            "merged_at": null,
            "closed_by": null,
            "closed_at": null,
            "target_branch": "master",
            "source_branch": "fix/plz-merge",
            "user_notes_count": 0,
            "upvotes": 0,
            "downvotes": 0,
            "author": {
                "id": 1,
                "name": "Authoring user",
                "username": "authoring-user",
                "state": "active",
                "avatar_url": "https://gitlab.example.org/uploads/-/system/user/avatar/1/authoring-user.jpg",
                "web_url": "https://gitlab.example.org/authoring-usr"
            },
            "assignees": [
                {
                    "id": 1,
                    "name": "Assigned User eg. bot",
                    "username": "assigned-user",
                    "state": "active",
                    "avatar_url": "https://gitlab.example.org/uploads/-/system/user/avatar/1/assigned-user.jpg",
                    "web_url": "https://gitlab.example.org/assigned-user"
                }
            ],
            "assignee": {
                    "id": 1,
                    "name": "Assigned User eg. bot",
                    "username": "assigned-user",
                    "state": "active",
                    "avatar_url": "https://gitlab.example.org/uploads/-/system/user/avatar/1/assigned-user.jpg",
                    "web_url": "https://gitlab.example.org/assigned-user"
            },
            "reviewers": [],
            "source_project_id": 461,
            "target_project_id": 461,
            "labels": [],
            "draft": false,
            "work_in_progress": false,
            "milestone": null,
            "merge_when_pipeline_succeeds": false,
            "merge_status": "can_be_merged",
            "sha": "bb414a9907033f76fc9357721d080444a05d9c26",
            "merge_commit_sha": null,
            "squash_commit_sha": null,
            "discussion_locked": null,
            "should_remove_source_branch": null,
            "force_remove_source_branch": true,
            "reference": "!679",
            "references": {
                "short": "!679",
                "relative": "!679",
                "full": "sample/project!679"
            },
            "web_url": "https://gitlab.example.org/sample/project/-/merge_requests/679",
            "time_stats": {
                "time_estimate": 0,
                "total_time_spent": 0,
                "human_time_estimate": null,
                "human_total_time_spent": null
            },
            "squash": false,
            "task_completion_status": {
                "count": 0,
                "completed_count": 0
            },
            "has_conflicts": false,
            "blocking_discussions_resolved": true,
            "changes_count": "1",
            "diff_refs": {
                "base_sha": "d94f419fc496589197e48306fd776574c4b6bcaa",
                "head_sha": "bb414a9907033f76fc9357721d080444a05d9c26",
                "start_sha": "d94f419fc496589197e48306fd776574c4b6bcaa"
            },
            "merge_error": null,
            "user": {
                "can_merge": false
            }
        },
        "target_url": "https://gitlab.example.org/sample/project/-/merge_requests/679",
        "body": "fix: plz merge",
        "state": "pending",
        "created_at": "2021-09-02T23:41:19.040+02:00",
        "updated_at": "2021-09-02T23:41:19.040+02:00"
    },
    {...}
]
```
</details>

**Comment by pepakriz** [comment]
Good idea! I'll look at it later, but it looks promising. User permission should be cached, so atomicity will not be achieved. But I hope It'll be OK for most situations.

**Comment by sandeep661** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @arnaud-devops, @dsoul, @Sweetspotproject, @Neno0o, @narendrapsgim, @nirmalrizal, @siddharths1, @kutyel, @joseph-rapach, @p4v4n, @stingray21, @0851, @overphoenix, @jasonmic2000, @nikku1234, @MatteoLeonesi, @forl, @kzmcond, @masaun, @IAMIBM, @Dev-Addi, @vovoska, @lionnung, @MandeepDalavi, @softhub-41, @Terry-Lzz, @kstudnik, @emanuelpinho, @lucahttp, @gptkrsh, @solidloco1, @seyyidibrahimgulec, @hannahnmcdonald, @narjirolu125, @Dex-Spirit, @andyluss, @iskitz, @mk-gt, @lujunzhan, @rxrangeles, @Plasma, @CT-66, @mdmannanmiya, @awray3, @nickolasburr, @dnlowman, @doylem, @Zjs555979, @imbahom, @ChenghaoMou

**Comment by pepakriz** [comment]
I'm working on it here: https://github.com/pepakriz/gitlab-merger-bot/pull/186
It introduces a new config flag because it changes the way how new assigned merge requests are discovered. I'll be testing this flag for a while.
