### ISSUE TITLE
Http Proxy Support

### ISSUE THREAD

**Issue by albthali** [pepakriz/gitlab-merger-bot#133]
We were looking for a tool that would help us automate merging requests in our organization once they passed our pipeline. We were so happy to find that you already solved this issue. Thank you so much for your efforts.

Needless to say, we could not immediately use this tool. Any request from any system in our organization has to go through our proxy. Since this project is using node-fetch, the only way to add [http proxy is to an agent](https://www.scrapingbee.com/blog/proxy-node-fetch/). To thank you for your work and to show our appreciation, we made those changes and in this [pull request.](https://github.com/pepakriz/gitlab-merger-bot/pull/132) The pull request includes the necessary changes to add Http proxy support to node-fetch. Furthermore, we have updated the helm chart to include settings.httpProxy value to add http proxy support.

It would be greatly appreciated if your could look over the pull request.

**Comment by pepakriz** [comment]
closed by https://github.com/pepakriz/gitlab-merger-bot/pull/134

Thank you!
