### ISSUE TITLE
Project still under maintenance?

### ISSUE THREAD

**Issue by Llois41** [pepakriz/gitlab-merger-bot#147]
Hi, this tool looks promising for our project. Is it still maintained since the last commit is from June 28, 2022 (disregarding the one dependabot PR in December). Will there be a stable v2 in the future?

**Comment by pepakriz** [comment]
Let's be honest. I maintain this project primarily for my personal purposes and for projects where I collaborate. So as long as this code fulfills our requirements, I don't have many incentives to implement more features.

However, I have currently made a major upgrade and I hope this will make it easier to maintain the project further.

About stable v2 - Maybe I could release it :)
