### ISSUE TITLE
Make Version 2 stable or add docs for stable version 1

### ISSUE THREAD

**Issue by Llois41** [pepakriz/gitlab-merger-bot#148]
I was very confused yesterday after deploying version 1.2.5 (latest stable) and trying to access the dashboard. After a few hours I realized that it was introduced in version 2.
Therefore it would be nice if the README implied that instead of implying "this is the current API" without differentiation of the two versions.

Is it possible to add some docs for the stable version 1 or even make version 2 stable?

Thanks in advance!

**Comment by pepakriz** [comment]
Currently, the stable version is not compatible with the current GitLab API. I'll release v2 as a stable version soon.
