### ISSUE TITLE
TLS too old / dependency upgrade requested for GitLab v16

### ISSUE THREAD

**Issue by gjrtimmer** [pepakriz/gitlab-merger-bot#151]
The bot cannot connect to GitLab 16.0.1.

## Error
```bash
GitLab request GET https://*********//api/v4/user failed: request to https://*********//api/v4/user failed, reason: write EPROTO 140458942532936:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1550:SSL alert number 70
```

## Reason
Base image and dependencies are too old, the bot cannot connect to newer versions because they are forcing higher levels of TLS ciphers and high TLS versions.

## Solution
- [ ] Upgrade dependencies
- [ ] Upgrade base node version
- [ ] Upgrade base alpine runtime image, request alpine:3.17

## Notes

I'm currently trying to make an upgrade, but I'm not well versed with NodeJS so I'm at a loss.

@pepakriz Could you please make an upgrade?

**Comment by pepakriz** [comment]
Hi @gjrtimmer 

Thanks for the report. I'm working on it (see https://github.com/pepakriz/gitlab-merger-bot/pull/152).

**Comment by pepakriz** [comment]
It's finally fixed on the latest version. The whole project has been upgraded to the latest libraries. I hope it'll simplify future maintenance.
